# Generated by Django 5.2.4 on 2025-07-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_options_alter_events_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table='events',
        ),
    ]
