# Generated by Django 5.2.4 on 2025-07-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=64),
            preserve_default=False,
        ),
    ]
