# Generated by Django 5.2.4 on 2025-07-29 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_attendees', '0001_initial'),
        ('events', '0003_alter_events_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventattendee',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.events'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='eventattendee',
            table='event_attendee',
        ),
    ]
